/*
The sequence of triangle numbers is generated by adding the 
natural numbers. So the 7th triangle number would be 
1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over 
five divisors. What is the value of the first triangle number 
to have over five hundred divisors?
*/

class PE012 {
  triangularNum(n) {
    return (n / 2) * (n + 1);
  }

  divisors(n) {
    if (n <= 0) return [];
    if (n === 1) return [1];
    const front = [1];
    const back = [n];
    for (let i = 2; i < Math.sqrt(n); i++) {
      if (n % i === 0) {
        front.push(i);
        back.unshift(n / i);
      }
    }
    if (Math.sqrt(n) % 1 === 0) {
      front.push(Math.sqrt(n));
    }
    return front.concat(back);
  }

  main(n) {
    let i = 1;
    while (this.divisors(this.triangularNum(i)).length <= n) {
      i++;
    }
    return this.triangularNum(i);
  }
}


// tests
test = new PE012();
console.log(test.divisors(1));
console.log(test.divisors(2));
console.log(test.divisors(3));
console.log(test.divisors(16));
console.log(test.divisors(28));
console.log(test.divisors(49));
console.log(test.main(5));
console.log(test.main(500)); // 76576500

