"""
Each new term in the Fibonacci sequence is generated by adding 
the previous two terms. By starting with 1 and 2, the first 10 
terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values 
do not exceed four million, find the sum of the even-valued terms.
"""


def fibonacci(n):
  if n <= 2:
    return n
  a = 1
  b = 2
  for _ in range(2, n):
    a, b = b, a + b
  return b


def fibonacci_gen():
  a = 1
  b = 2
  yield a
  yield b
  while (1):
    a, b = b, a + b
    yield b


def PE002(ceiling):
  fib = fibonacci_gen()
  num = next(fib)
  sum = 0
  while num < ceiling:
    if not num & 1:
      sum += num
    num = next(fib)
  return sum


PE002(4000000)  # 4613732
